

SET ECHO ON
SET FEEDBACK 1
SET NUMWIDTH 10
SET LINESIZE 80
SET TRIMSPOOL ON
SET TAB OFF
SET PAGESIZE 100

CREATE OR REPLACE DIRECTORY data_file_dir AS '__SUB__CWD__/sales_history/'; 
CREATE OR REPLACE DIRECTORY log_file_dir  AS '__SUB__CWD__/log/'; 
CREATE OR REPLACE DIRECTORY media_dir     AS '__SUB__CWD__/product_media/';

GRANT READ ON DIRECTORY media_dir      TO pm;
GRANT READ ON DIRECTORY log_file_dir   TO sh;
GRANT READ ON DIRECTORY data_file_dir  TO sh;  
GRANT WRITE ON DIRECTORY log_file_dir  TO sh;
EXECUTE DBMS_DATAPUMP_UTL.REPLACE_DEFAULT_DIR;
EXECUTE ORACLE_OCM.MGMT_CONFIG_UTL.create_replace_dir_obj;
