

SET FEEDBACK 1
SET NUMWIDTH 10
SET LINESIZE 80
SET TRIMSPOOL ON
SET TAB OFF
SET PAGESIZE 100

PROMPT
PROMPT specify password for oe as parameter 1:
DEFINE oe_pass             = &1
PROMPT
PROMPT specify connect string as parameter 2:
DEFINE connect_string     = &2
PROMPT

CONNECT oe/&oe_pass@&connect_string;

GRANT SELECT ON BOMBAY_INVENTORY TO bi;
GRANT SELECT ON CUSTOMERS TO bi;
GRANT SELECT ON INVENTORIES TO bi;
GRANT SELECT ON ORDERS TO bi;
GRANT SELECT ON ORDER_ITEMS TO bi;
GRANT SELECT ON PRODUCTS TO bi;
GRANT SELECT ON PRODUCT_DESCRIPTIONS TO bi;
GRANT SELECT ON PRODUCT_INFORMATION TO bi;
GRANT SELECT ON PRODUCT_PRICES TO bi;
GRANT SELECT ON PROMOTIONS TO bi;
GRANT SELECT ON SYDNEY_INVENTORY TO bi;
GRANT SELECT ON TORONTO_INVENTORY TO bi;
GRANT SELECT ON WAREHOUSES TO bi;

COMMIT;
